config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "forms", to: "forms#index"
  get "forms/:survey_token/edit", to: "forms#edit", as: :form
  post "forms/:survey_token/responses", to: "survey_responses#create", as: :form_responses

  resources :surveys, only: [:index, :new, :edit, :create, :update]
  get "surveys/:id/responses", to: "surveys#responses", as: :survey_responses
  get "surveys/:id/download", to: "surveys#download", as: :survey_download

  get "login", to: "sessions#new"
  post "sessions", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  namespace :api, {format: "json"} do
    post "surveys/:id", to: "surveys#update", as: :survey
    get "survey_responses", to: "survey_responses#index"
  end
end

app/views/shared/admin_menu_modal.html.erb
<div id="<%= modal_id %>" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t('.title') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          <%= t('.login_as', value: current_user.email) %><br>
          <br>
          <%= link_to t('.admin_link'), surveys_path %>
          <span class="text-muted"><%= t('.admin_required') %></span><br>
          <br>
          <%= link_to t('.guest_link'), forms_path %>
          <span class="text-muted"><%= t('.for_guest') %></span><br>
          <br>
          <%= link_to t('.logout'), logout_path, class: 'text-danger' %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"><%= t('.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/download_responses_modal.html.erb
<div id="<%= modal_id %>" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t('.title') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          <%= t('.message') %><br>
          <br>
          <%= t('.duration') %><br>
          <%= t('.limit', value: 100000.to_fs(:delimited)) %>
        </p>
        <%= link_to t('.download'), download_url, class: 'btn btn-primary' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"><%= t('.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/manage_denied_ips_modal.html.erb
<div id="<%= modal_id %>" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t('.title') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          <%= t('.cond_title', value: 1) %>:<br>
          <%= t('.cond1') %><br>
          <br>
          <%= t('.cond_title', value: 2) %>:<br>
          <%= t('.cond2') %><br>
          <br>
          <span class="small text-danger"><%= t('.note') %></span>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal"><%= t('.close') %></button>
      </div>
    </div>
  </div>
</div>