config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "forms", to: "forms#index"
  get "forms/:survey_token/edit", to: "forms#edit", as: :form
  post "forms/:survey_token/responses", to: "survey_responses#create", as: :form_responses

  resources :surveys, only: [:index, :new, :edit, :create, :update]
  get "surveys/:id/responses", to: "surveys#responses", as: :survey_responses
  get "surveys/:id/download", to: "surveys#download", as: :survey_download

  get "login", to: "sessions#new"
  post "sessions", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  namespace :api, {format: "json"} do
    post "surveys/:id", to: "surveys#update", as: :survey
    get "survey_responses", to: "survey_responses#index"
  end
end

app/models/survey.rb
require 'digest/md5'

class Survey < ApplicationRecord
  has_many :questions
  has_many :survey_responses

  validates :title, presence: true
  validates :description, presence: true

  DEFAULT_QUESTIONS = 10

  before_create do
    if survey_token.blank?
      self.survey_token = Digest::MD5.hexdigest(Time.zone.now.to_i.to_s)
    end
  end

  class << self
    def find_by_token(token)
      find_by(survey_token: token)
    end
  end

  def to_filename
    prefix = title.gsub(/[ 　]/, '_')
    time = Time.zone.now.in_time_zone('Tokyo').strftime("%Y%m%d%H%M%S")
    "#{prefix}-#{time}.csv"
  rescue => e
    'Results.csv'
  end
end

app/controllers/Api/surveys_controller.rb
module Api
  class SurveysController < BaseController
    def update
      survey = Survey.find(params[:id])
      survey.update(is_public: parse_boolean(params[:is_public]))
      render json: {id: survey.id, is_public: survey.is_public}
    end

    private

    def parse_boolean(value)
      if value == 'true'
        true
      elsif value == 'false'
        false
      else
        raise
      end
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include SurveyResponsesHelper

  before_action :authenticate_user!

  def index
    @surveys = Survey.order(created_at: :desc).limit(300)
  end

  def show
  end

  def responses
    @survey = Survey.includes(:questions).find(params[:id])
  end

  def download
    survey = Survey.includes(:questions).find(params[:id])
    send_data csv_data(survey), filename: survey.to_filename, type: 'text/csv; charset=utf-8'
  end

  def new
    @survey = Survey.new(is_public: false)
    Survey::DEFAULT_QUESTIONS.times { @survey.questions.build }
    @survey.questions[0].is_required = true
  end

  def edit
    @survey = Survey.includes(:questions).find(params[:id])
  end

  def create
    @survey = Survey.new(survey_params)

    questions =
        params[:questions].select { |q| sanitize_question(q[:title]).present? }.map do |question|
          Question.new(title: sanitize_question(question[:title]), field_type: parse_field_type(question[:field_type]), is_required: question[:is_required])
        end

    error = nil

    begin
      Survey.transaction do
        @survey.save!
        @survey.questions = questions
      end
    rescue => e
      logger.warn e.inspect
      error = e
    end

    if error
      render :new, status: :unprocessable_entity
    else
      redirect_to surveys_path, notice: t('.create.saved')
    end
  end

  def update
    @survey = Survey.includes(:questions).find(params[:id])
    @survey.assign_attributes(survey_params)

    error = nil

    begin
      @survey.save!
    rescue => e
      logger.warn e.inspect
      error = e
    end

    if error
      render :edit, status: :unprocessable_entity
    else
      redirect_to edit_survey_path(id: @survey.id), notice: t('.update.saved')
    end
  end

  def destroy
    @survey.destroy
    redirect_to surveys_url, notice: "Survey was successfully destroyed."
  end

  private

  def sanitize_question(text)
    ApplicationController.helpers.strip_tags(text).chomp
  end

  def parse_field_type(value)
    value == 'text_area' ? 'text_area' : 'text'
  end

  def survey_params
    params.require(:survey).permit(:title, :description, :is_public)
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def auto_link_description(survey)
    # TODO Fix performance issue
    auto_link(survey.description.gsub(/\r?\n/, '<br>'), link: :urls, html: {target: '_blank'})
  end
end

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div style="color: red">
      <h2 class="h4"><%= t('.error') %></h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card card-body rounded-1rem my-5">
    <div class="mb-5">
      <label class="form-label"><%= t('.title') %> <span class="text-danger">*</span></label>
      <%= form.text_field :title, class: 'form-control', value: survey.title || t('.title_placeholder'), required: true %>
    </div>

    <div class="mb-5">
      <label class="form-label"><%= t('.description') %> <span class="text-danger">*</span></label>
      <%= form.text_area :description, class: 'form-control', value: survey.description || t('.description_placeholder'), rows: 20, required: true %>
      <div class="form-text"><%= t('.description_note') %></div>
    </div>


    <div>
      <div class="d-inline-block" style="min-width: 200px;">
        <label class="form-label"><%= t('.is_public') %></label>
        <%= form.select :is_public, options_for_select([[t('.is_public_true'), 'true'], [t('.is_public_false'), 'false']], survey.is_public), {}, class: 'form-select' %>
      </div>
      <div class="form-text"><%= t('.is_public_note') %></div>
    </div>
  </div>

  <div class="text-danger my-5">
    <%= t('.questions_fixed') %><br>
    <br>
    <%= t('.one_question_required') %>
  </div>

  <% survey.questions.each.with_index do |question, n| %>
    <div class="card card-body rounded-1rem my-5">
      <div class="d-flex">
        <div class="text-nowrap me-3">
          <label class="col-form-label">
            <%= t('.question.title', count: n + 1) %>
            <% if question.is_required %>
              <span class="text-danger">*</span>
            <% end %>
          </label>
        </div>
        <div class="w-100">
          <%= text_field_tag 'questions[][title]', (n == 0 ? t('.question.whats_your_name') : ''), class: 'form-control', required: question.is_required, disabled: action_name == 'edit' %>
        </div>
      </div>

      <select class="form-select mt-3" name="questions[][field_type]" style="display: inline-block; width: 200px;" <%= 'disabled' if action_name == 'edit' %>>
        <option value="text" <%= 'selected' if question.field_type == 'text' %>><%= t('.question.field_type_text') %></option>
        <option value="text_area" <%= 'selected' if question.field_type == 'text_area' %>><%= t('.question.field_type_multiple') %></option>
      </select>

      <div class="form-check mt-3">
        <%= check_box_tag 'questions[][is_required]', true, question.is_required, {id: "question-#{n}_is_required", class: 'form-check-input', disabled: action_name == 'edit'} %>
        <label class="form-check-label" for="<%= "question-#{n}_is_required" %>">
          <%= t('.question.is_required_label') %>
        </label>
      </div>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.submit t('.submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
</div>

app/views/surveys/edit.html.erb
<div class="container my-5">
  <div class="my-3"><%= link_to t('.back'), surveys_path %></div>

  <% if notice %>
    <div class="alert alert-success my-5" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="h3 my-5"><%= t('.page_title') %></h1>
  <%= render "form", survey: @survey %>
</div>

app/views/surveys/index.html.erb
<div class="container my-5">
  <% if notice %>
    <div class="alert alert-success my-5" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="h3 my-5"><%= t('.page_title') %></h1>

  <div class="my-3">
    <%= link_to t('.new'), new_survey_path, class: 'btn btn-primary' %>
  </div>

  <div class="my-3">
    <%= link_to t('.manage_denied_ip'), new_survey_path, class: 'btn btn-outline-danger', 'data-bs-toggle' => 'modal', 'data-bs-target' => '#manage-denied-ips-modal' %>
  </div>

  <%= render template: 'shared/manage_denied_ips_modal', locals: {modal_id: 'manage-denied-ips-modal'} %>

  <% @surveys.each do |survey| %>
    <div class="card rounded-1rem my-5">
      <div class="card-body">

        <div class="form-check form-switch">
          <input id="<%= "survey_is_public-#{survey.id}" %>" class="survey_is_public form-check-input" type="checkbox" data-id="<%= survey.id %>" <%= 'checked' if survey.is_public %>>
          <label class="form-check-label" for="<%= "survey_is_public-#{survey.id}" %>">
            <%= survey.is_public ? t('.is_public') : t('.is_private') %>
          </label>
        </div>

        <hr>

        <div class="small text-muted mb-3"><%= t('.created') %><%= survey.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M") %></div>
        <h5 class="card-title mb-3"><%= survey.title %></h5>
        <p class="card-text"><%= auto_link_description(survey) %></p>

        <hr>

        <div class="row">
          <div class="col-6 col-md-3">
            <%= link_to edit_survey_path(id: survey.id) do %>
              <i class="fa-regular fa-pen-to-square"></i>
              <%= t('.edit') %>
            <% end %>
          </div>
          <div class="col-6 col-md-3">
            <%= link_to form_path(survey_token: survey.survey_token) do %>
              <i class="fa-regular fa-eye"></i>
              <%= t('.preview', value: survey.questions.size) %>
            <% end %>
          </div>
          <div class="col-6 col-md-3">
            <%= link_to survey_responses_path(id: survey.id) do %>
              <i class="fa-regular fa-envelope"></i>
              <%= t('.responses', value: survey.survey_responses.size) %>
            <% end %>
          </div>
          <div class="col-6 col-md-3">
            <%= link_to '#', class: 'btn-copy-url', data: {id: survey.id, url: form_url(survey_token: survey.survey_token)} do %>
              <i class="fa-regular fa-copy"></i>
              <%= t('.copy') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(function () {
    $('.survey_is_public').on('click', function () {
      var url = '<%= api_survey_path(id: '__ID__') %>';
      var labels = {
        isPublic: '<%= t('.is_public') %>',
        isPrivate: '<%= t('.is_private') %>'
      };

      var id = $(this).data('id');
      var checked = $(this).prop('checked');
      url = url.replace('__ID__', id);
      console.log({id: id, checked: checked, url: url});

      $.post(url, {is_public: checked}).done(function (res) {
        console.log(res);
        var $label = $('label[for="survey_is_public-' + id + '"]')
        if (checked) {
          $label.text(labels['isPublic']);
        } else {
          $label.text(labels['isPrivate']);
        }
      }).fail(function (xhr) {
        console.error(xhr);
      });
    });

    $('.btn-copy-url').on('click', function (e) {
      e.preventDefault();
      e.stopPropagation();

      var id = $(this).data('id');
      var url = $(this).data('url');
      var messages = {
        succeeded: '<%= t('.copy_succeeded') %>',
        isNotPublic: '<%= t('.is_not_public') %>',
        failed: '<%= t('.copy_failed') %>'
      }

      var checked = $('input#survey_is_public-' + id).prop('checked');
      if (!checked) {
        alert(messages['isNotPublic']);
        return false;
      }

      if (navigator.clipboard) {
        navigator.clipboard.writeText(url).then(function () {
          alert(messages['succeeded']);
        }).catch(function () {
          alert(messages['failed']);
        });
      } else {
        document.execCommand("Copy");
        alert(messages['succeeded']);
      }
    });
  });
</script>

app/views/surveys/new.html.erb
<div class="container my-5">
  <div class="my-3"><%= link_to t('.back'), surveys_path %></div>

  <h1 class="h3 my-5"><%= t('.page_title') %></h1>
  <%= render "form", survey: @survey %>
</div>

app/views/surveys/responses.html.erb
<div class="container my-5">
  <div class="my-3"><%= link_to t('.back'), surveys_path %></div>

  <h1 class="h3 my-5"><%= @survey.title %></h1>

  <div class="my-3">
    <%= t('.download_html', modal_id: 'download-responses-modal') %>
  </div>

  <%= render template: 'shared/download_responses_modal', locals: {modal_id: 'download-responses-modal', download_url: survey_download_path(id: @survey.id, duration: '30_days', limit: 100000)} %>

  <div class="my-3">
    <div class="input-group">
      <span class="input-group-text" id="basic-addon1"><%= t('.search.word') %></span>
      <input type="text" class="form-control" id="search-word">
    </div>
    <div class="form-text"><%= t('.search.word_note') %></div>
  </div>

  <div class="d-inline-block">
    <div class="input-group my-3">
      <label class="input-group-text" for="inputGroupSelect01"><%= t('.search.duration') %></label>
      <select class="form-select" id="select-duration">
        <option value="7_days" selected><%= t('.search.7_days') %></option>
        <option value="30_days"><%= t('.search.30_days') %></option>
      </select>
    </div>
  </div>

  <div>
    <div class="d-inline-block">
      <div class="input-group my-3">
        <label class="input-group-text" for="inputGroupSelect02"><%= t('.search.limit') %></label>
        <select class="form-select" id="select-limit">
          <option value="100" selected><%= t('.search.limit_n', value: 100) %></option>
          <option value="1000"><%= t('.search.limit_n', value: 1000.to_fs(:delimited)) %></option>
          <option value="10000"><%= t('.search.limit_n', value: 10000.to_fs(:delimited)) %></option>
        </select>
      </div>
    </div>
  </div>

  <div id="error-message" class="text-danger my-5" style="display: none;"></div>

  <div class="table-responses-wrapper my-5">
    <table class="table-responses bg-white">
      <thead>
      <tr>
        <td><%= t('.number') %></td>
        <td><%= t('.time') %></td>
        <td><%= t('.ip') %></td>
        <td><%= t('.browser') %></td>
        <td><%= t('.os') %></td>
        <td><%= t('.device_type') %></td>
        <% @survey.questions.each do |question| %>
          <td style="min-width: 150px;"><%= question.title %></td>
        <% end %>
      </tr>
      </thead>
    </table>
  </div>
</div>

<script>
  $(function () {
    var table;
    var messages = {
      fetchingFailed: '<%= t('.fetching_failed') %>'
    }

    function fetchData(callback) {
      var url = '<%= api_survey_responses_path(id: @survey.id) %>';
      url += '&q=' + encodeURIComponent($('#search-word').val());
      url += '&duration=' + $('#select-duration').val();
      url += '&limit=' + $('#select-limit').val();
      console.log('url', url);

      $.get(url).done(function (res) {
        console.log('res', res);
        $('#error-message').empty().hide();
        callback(res);
      }).fail(function (xhr) {
        console.error(xhr);
        $('#error-message').empty().text(messages['fetchingFailed']).show();
        callback({data: []})
      });
    }

    function updateTable() {
      var questionIds = <%= @survey.questions.map(&:id).to_json %>;
      var columns = [
        {data: 'number'},
        {data: 'time'},
        {data: 'ip'},
        {data: 'browser'},
        {data: 'os'},
        {data: 'device_type'}
      ];

      questionIds.forEach(function (id) {
        columns.push({data: 'question-' + id})
      });
      console.log('columns', columns);

      table = $('.table-responses').DataTable({
        ajax: function (data, callback, settings) {
          fetchData(callback);
        },
        columns: columns,
        columnDefs: [
          {targets: [0, 1, 2, 3, 4, 5], className: 'text-nowrap'},
        ],
        order: [[1, 'desc']],
        lengthChange: false,
        searching: false,
        info: false,
        paging: false
      });
    }

    $('#search-word, #select-duration, #select-limit').on('change', function () {
      table.ajax.reload();
    });

    updateTable();
  });
</script>

app/views/surveys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey %>

<div>
  <%= link_to "Edit this survey", edit_survey_path(@survey) %> |
  <%= link_to "Back to surveys", surveys_path %>

  <%= button_to "Destroy this survey", @survey, method: :delete %>
</div>