config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "forms", to: "forms#index"
  get "forms/:survey_token/edit", to: "forms#edit", as: :form
  post "forms/:survey_token/responses", to: "survey_responses#create", as: :form_responses

  resources :surveys, only: [:index, :new, :edit, :create, :update]
  get "surveys/:id/responses", to: "surveys#responses", as: :survey_responses
  get "surveys/:id/download", to: "surveys#download", as: :survey_download

  get "login", to: "sessions#new"
  post "sessions", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  namespace :api, {format: "json"} do
    post "surveys/:id", to: "surveys#update", as: :survey
    get "survey_responses", to: "survey_responses#index"
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
    @surveys = Survey.where(is_public: true).order(created_at: :desc).limit(100)
  end

  def edit
    @survey = Survey.includes(:questions).find_by_token(params[:survey_token])

    unless @survey
      render 'not_found', status: :not_found
      return
    end

    if !user_signed_in? && !@survey.is_public
      render 'expired'
    end
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  def question_field_tag(type, name, id:, _class:, required: false)
    if type == 'text'
      text_field_tag name, '', id: id, class: _class, required: required
    else
      text_area_tag(name, '', id: id, class: _class, rows: 10, required: required)
    end
  end
end

app/views/forms/edit.html.erb
<div class="container my-5">
  <% if notice %>
    <div class="alert alert-success my-5" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% unless @survey.is_public %>
    <p class="text-danger my-5"><%= t('.expired_note') %></p>
  <% end %>

  <div class="my-3"><%= link_to t('.back'), forms_path %></div>

  <div class="card rounded-1rem my-5">
    <div class="card-body">
      <h5 class="card-title mb-3"><%= @survey.title %></h5>
      <p class="card-text"><%= auto_link_description(@survey) %></p>
    </div>
  </div>

  <%= form_tag form_responses_path(survey_token: @survey.survey_token), method: :post do %>
    <% @survey.questions.each do |question| %>
      <% question_id = "question-#{question.id}" %>

      <div class="card card-body rounded-1rem my-5">
        <label for="<%= question_id %>" class="form-label">
          <%= question.title %>
          <% if question.is_required %>
            <span class="text-danger">*</span>
          <% end %>
        </label>
        <%= question_field_tag(question.field_type, 'answers[][message]', id: question_id, _class: 'form-control', required: question.is_required) %>
        <% if question.note %>
          <div class="form-text"><%= question.note %></div>
        <% end %>

        <%= hidden_field_tag 'answers[][question_id]', question.id %>
      </div>
    <% end %>

    <%= submit_tag t('.submit'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/forms/expired.html.erb
<div class="container my-5">
  <div class="my-3"><%= link_to t('.back'), forms_path %></div>

  <div class="card rounded-1rem my-5">
    <div class="card-body">
      <h5 class="card-title"><%= @survey.title %></h5>
      <p class="card-text"><%= t('.message') %></p>
    </div>
  </div>
</div>

app/views/forms/index.html.erb
<div class="container my-5">
  <h1 class="h3 my-5"><%= t('.page_title') %></h1>

  <% if @surveys.any? %>
    <% @surveys.each do |survey| %>
      <div class="card rounded-1rem my-5">
        <div class="card-body">
          <h5 class="card-title mb-3"><%= survey.title %></h5>
          <p class="card-text"><%= auto_link_description(survey) %></p>
          <%= link_to t('.answer'), form_path(survey_token: survey.survey_token), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= t('.empty_surveys') %>
  <% end %>
</div>

app/views/forms/not_found.html.erb
<div class="container my-5">
  <div class="my-3"><%= link_to t('.back'), forms_path %></div>

  <div class="card rounded-1rem my-5">
    <div class="card-body">
      <p class="card-text"><%= t('.message') %></p>
    </div>
  </div>
</div>